# Generated by Django 5.0.2 on 2024-03-13 13:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminsight_api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='sysuser',
            name='system',
            field=models.ForeignKey(default=2, on_delete=django.db.models.deletion.CASCADE, to='adminsight_api.system'),
            preserve_default=False,
        ),
    ]
