# Generated by Django 5.0.2 on 2024-03-14 11:38

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminsight_api', '0002_sysuser_system'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='system',
            name='app_users',
            field=models.ManyToManyField(related_name='systems', through='adminsight_api.AppUserSystem', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterUniqueTogether(
            name='appusersystem',
            unique_together={('app_user', 'system')},
        ),
    ]
